// @ts-check
import js from '@eslint/js';
import tseslint from 'typescript-eslint';

export default tseslint.config(
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/.next/**',
      '**/.turbo/**',
      '**/coverage/**',
      '**/playwright-report/**',
      '**/test-results/**',
      '**/.venv/**',
      '**/__pycache__/**',
      'pnpm-lock.yaml',
      // Auto-generated by `next dev` / `next build`. Uses triple-slash
      // references that the @typescript-eslint/triple-slash-reference rule
      // flags. Standard Next.js pattern is to commit but not lint this file.
      '**/next-env.d.ts',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      parserOptions: {
        ecmaFeatures: { jsx: true },
      },
    },
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      '@typescript-eslint/consistent-type-imports': 'warn',
    },
  },
  // Plain JS/MJS/CJS files in this repo are Node-side (configs + build scripts,
  // e.g. apps/web/next.config.mjs). typescript-eslint disables `no-undef` for
  // .ts via type info, but JS files need Node globals declared so references
  // like `process.env` don't trip no-undef.
  {
    files: ['**/*.{js,cjs,mjs}'],
    languageOptions: {
      globals: {
        process: 'readonly',
        console: 'readonly',
        Buffer: 'readonly',
        URL: 'readonly',
        __dirname: 'readonly',
        __filename: 'readonly',
        module: 'writable',
        require: 'readonly',
        exports: 'writable',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
      },
    },
  },
  // ADR-0002 follow-up: only @alphawolf/db may import @prisma/client. Bare
  // imports elsewhere bypass the RLS session-variable middleware and become
  // a security bug.
  {
    files: ['**/*.{ts,tsx,js,jsx,mjs,cjs}'],
    ignores: ['packages/db/**'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          paths: [
            {
              name: '@prisma/client',
              message:
                'Import from @alphawolf/db instead. Bare @prisma/client bypasses the RLS session-variable middleware (ADR-0002).',
            },
          ],
          patterns: [
            {
              group: ['@prisma/client/*'],
              message:
                'Import from @alphawolf/db instead. Bare @prisma/client bypasses the RLS session-variable middleware (ADR-0002).',
            },
          ],
        },
      ],
    },
  },
  // PR #39 follow-up: third-party observability (Sentry) bypasses the
  // pgcrypto/PII encryption boundary unless every init scrubs. These guards
  // catch the two regressions: turning sendDefaultPii back on, and adding a
  // Sentry.init that forgets the shared scrubber. See
  // packages/observability/src/sentry-scrub.ts and ADR-0011.
  {
    files: ['**/*.{ts,tsx,js,jsx,mjs,cjs}'],
    rules: {
      'no-restricted-syntax': [
        'error',
        {
          selector: "Property[key.name='sendDefaultPii'][value.value=true]",
          message:
            'Sentry sendDefaultPii must be false. Use the shared scrubber instead — see packages/observability/src/sentry-scrub.ts.',
        },
        {
          selector:
            "CallExpression[callee.object.name='Sentry'][callee.property.name='init'] > ObjectExpression:not(:has(Property[key.name='beforeSend']))",
          message:
            'Every Sentry.init must pass beforeSend: scrubSentryEvent (from @alphawolf/observability).',
        },
      ],
    },
  },
);
