// Studio authoring assembly (Goal 6): payload validation, calibrated areas,
// wrap-safe generation, and the build->validate round trip — all pure, no DB.

import { describe, expect, it } from 'vitest';
import type { VehicleDetail } from '@alphawolf/db';
import { assembleOutline } from '@/lib/studio/author';
import { assembleLayoutSheet } from '@/lib/studio/layout';

const BOAT: VehicleDetail = {
  id: 'aa000002-0000-4000-8000-000000000002',
  year: 2024,
  make: 'Contender',
  model: "36.5' Bass Boat",
  trim: null,
  variant: null,
  bodyType: 'boat',
  lengthMm: 11125,
  widthMm: 3050,
  heightMm: 2400,
  outlineSvgUrl: 'https://example.test/outline.svg',
  thumbPngUrl: 'https://example.test/thumb.png',
  status: 'published',
  version: 1,
  svgStorageKey: 'aa000002-0000-4000-8000-000000000002/wrapped.svg',
  viewCount: 2,
  dimensionsText: null,
  scaleDenom: 20,
  alphaWolfTplId: 'AW-TPL-0002',
  wheelbaseMm: null,
  cabSize: null,
  bedSize: null,
  roofHeight: null,
  doorCount: null,
  topviewSvgUrl: null,
  sourceAuthority: 'licensed',
  sourceNotes: null,
  verifiedAt: null,
  supersedesId: null,
  createdAt: new Date('2026-06-01'),
  updatedAt: new Date('2026-06-01'),
  panels: [],
};

// Port profile spans 1390 units of an 11,125 mm boat → 8.0036 mm/unit.
const SPAN_UNITS = 1390;
const MM_PER_UNIT = 11125 / SPAN_UNITS;

const VALID_PAYLOAD = {
  viewBox: { width: 1920, height: 1080 },
  provenanceNote: 'Authored over Alpha Wolf owned wrapped art (aa000002/wrapped.svg).',
  views: [
    {
      view: 'driver',
      translate: { x: 0, y: 60 },
      spanUnits: SPAN_UNITS,
      panels: [
        {
          name: 'Port Hull',
          outlinePath: 'M100 300 L800 300 L800 460 L100 460 Z',
          wrapSafePath: 'M110 310 L790 310 L790 450 L110 450 Z',
          finishHint: 'gloss',
          installOrder: 1,
        },
      ],
    },
    {
      view: 'passenger',
      translate: { x: 0, y: 560 },
      spanUnits: SPAN_UNITS,
      panels: [
        {
          name: 'Starboard Hull',
          outlinePath: 'M100 300 L800 300 L800 460 L100 460 Z',
          // wrapSafePath omitted -> generated by 12 mm calibrated inset.
          finishHint: 'satin',
          installOrder: 2,
        },
      ],
    },
  ],
};

describe('assembleOutline', () => {
  it('assembles, validates, and calibrates a 2-view payload', () => {
    const result = assembleOutline(BOAT, VALID_PAYLOAD);
    expect(result.ok).toBe(true);
    if (!result.ok) return;
    const { assembled } = result;

    expect(assembled.declaredViews).toEqual(['driver', 'passenger']);
    expect(assembled.panels).toHaveLength(2);
    expect(assembled.mmPerUnitByView.driver).toBeCloseTo(MM_PER_UNIT, 4);

    // Explicit wrap-safe: 680×140 units → real mm² via calibration.
    const port = assembled.panels.find((p) => p.name === 'Port Hull')!;
    expect(port.printableAreaMm2).toBe(Math.round(680 * 140 * MM_PER_UNIT * MM_PER_UNIT));
    expect(port.wrapSafeZone).toEqual({
      clip_path: 'M110 310 L790 310 L790 450 L110 450 Z',
      inset_mm: 12,
    });

    // Generated wrap-safe: a 12 mm inset = 12/MM_PER_UNIT ≈ 1.5 units a side.
    const starboard = assembled.panels.find((p) => p.name === 'Starboard Hull')!;
    const insetUnits = 12 / MM_PER_UNIT;
    const expectedArea =
      (700 - 2 * insetUnits) * (160 - 2 * insetUnits) * MM_PER_UNIT * MM_PER_UNIT;
    // The generated inset rounds path coords to 2 decimals — allow ±500 mm²
    // on a ~7 m² panel (0.01%).
    expect(starboard.printableAreaMm2).toBeCloseTo(expectedArea, -3);

    // The generated document round-tripped the validator.
    expect(assembled.svgText).toContain('data-view="driver"');
    expect(assembled.svgText).toContain('Provenance:');
  });

  it('rejects a payload with duplicate views', () => {
    const bad = {
      ...VALID_PAYLOAD,
      views: [VALID_PAYLOAD.views[0], VALID_PAYLOAD.views[0]],
    };
    const result = assembleOutline(BOAT, bad);
    expect(result.ok).toBe(false);
    if (!result.ok) expect(result.errors[0]?.message).toMatch(/Duplicate view/);
  });

  it('rejects malformed path data via the schema', () => {
    const bad = structuredClone(VALID_PAYLOAD) as Record<string, unknown>;
    (bad.views as Array<{ panels: Array<{ outlinePath: string }> }>)[0]!.panels[0]!.outlinePath =
      'M10 banana';
    const result = assembleOutline(BOAT, bad);
    expect(result.ok).toBe(false);
    if (!result.ok) expect(result.errors.some((e) => /path/i.test(e.message))).toBe(true);
  });

  it('rejects a too-short provenance note (license wall)', () => {
    const result = assembleOutline(BOAT, { ...VALID_PAYLOAD, provenanceNote: 'mine' });
    expect(result.ok).toBe(false);
  });

  it('reports calibration failures per view', () => {
    const bad = structuredClone(VALID_PAYLOAD) as { views: Array<{ spanUnits: number }> };
    bad.views[0]!.spanUnits = -5;
    const result = assembleOutline(BOAT, bad as unknown);
    expect(result.ok).toBe(false);
  });

  it('surfaces a wrap-safe inset failure with the panel name', () => {
    // A sliver outline narrower than 2×12mm cannot take the generated inset.
    const bad = structuredClone(VALID_PAYLOAD) as {
      views: Array<{ panels: Array<{ name: string; outlinePath: string; wrapSafePath?: string }> }>;
    };
    bad.views[1]!.panels[0] = {
      name: 'Sliver Trim',
      outlinePath: 'M100 300 L800 300 L800 302 L100 302 Z',
    };
    const result = assembleOutline(BOAT, bad as unknown);
    expect(result.ok).toBe(false);
    if (!result.ok) {
      expect(result.errors.some((e) => e.message.includes('Sliver Trim'))).toBe(true);
    }
  });
});

describe('assembleLayoutSheet', () => {
  it('lays views in a row with real-dimension callouts and the AW code', () => {
    const withPanels: VehicleDetail = {
      ...BOAT,
      panels: [
        {
          id: 'p1',
          name: 'Port Hull',
          view: 'driver',
          svgPath: 'M100 300 L800 300 L800 460 L100 460 Z',
          wrapSafeZone: { clip_path: 'M110 310 L790 310 L790 450 L110 450 Z', inset_mm: 12 },
          printableAreaMm2: 6_096_000,
          finishHint: 'gloss',
          installOrder: 1,
          notes: null,
        },
        {
          id: 'p2',
          name: 'Starboard Hull',
          view: 'passenger',
          svgPath: 'M100 300 L800 300 L800 460 L100 460 Z',
          wrapSafeZone: { clip_path: 'M110 310 L790 310 L790 450 L110 450 Z', inset_mm: 12 },
          printableAreaMm2: 6_096_000,
          finishHint: 'gloss',
          installOrder: 2,
          notes: null,
        },
      ],
    };
    const sheet = assembleLayoutSheet(withPanels);
    expect(sheet.code).toBe('AW-TPL-0002');
    expect(sheet.scaleDenom).toBe(20);
    expect(sheet.viewsLine).toBe('2-View · Driver / Passenger');
    expect(sheet.views).toHaveLength(2);
    // Profile views call out the overall length in mm + inches.
    expect(sheet.views[0]?.annotations?.[0]).toEqual({
      kind: 'length',
      label: 'Overall length 11,125 mm · 438.0 in',
    });
    // Second view starts one content-width + gutter to the right.
    expect(sheet.views[1]?.translate.x).toBeGreaterThan(sheet.views[0]!.translate.x);
  });
});
