// Template Studio authoring assembly (Goal 6). Pure module — no 'use server',
// no DB access — so the payload→outline-SVG→panel-rows pipeline is unit-tested
// directly and the Server Action stays a thin authz + persistence shell.
//
// Flow: the Studio UI (or the AW authoring script) submits a StudioAuthorPayload;
// this module generates missing wrap-safe paths (12 mm inset via the calibrated
// mm-per-unit), serialises the outline SVG, round-trips it through the §3.4
// validator with the declared views, and converts the extracted panels into
// vehicles.PanelInput rows with CALIBRATED real-mm² printable areas.

import { geometry } from '@alphawolf/canvas';
import { svg, type PanelInput, type VehicleDetail } from '@alphawolf/db';
import { z } from 'zod';

// 12 mm is the spec's wrap-safe default inset (vehicle-database-spec §6 step 4).
const WRAP_SAFE_INSET_MM = 12;

const pathField = z
  .string()
  .min(1)
  .max(20_000)
  .refine((d) => svg.isValidPathData(d), 'malformed SVG path data');

const panelSchema = z.object({
  name: z.string().trim().min(1).max(80),
  outlinePath: pathField,
  // Omitted → generated by insetting the outline 12 mm (calibrated).
  wrapSafePath: pathField.optional(),
  finishHint: z
    .enum(['gloss', 'satin', 'matte', 'chrome', 'carbon', 'brushed', 'none'])
    .default('gloss'),
  installOrder: z.number().int().min(1).max(99).optional(),
  notes: z.string().trim().max(500).optional(),
});

const viewSchema = z.object({
  view: z.enum(['front', 'driver', 'back', 'passenger', 'top']),
  translate: z.object({ x: z.number().finite(), y: z.number().finite() }).default({ x: 0, y: 0 }),
  // Calibration: the document-unit span of the vehicle silhouette in this view
  // and which real dimension it represents (defaults per defaultAxisForView).
  spanUnits: z.number().positive(),
  axis: z.enum(['length', 'width', 'height']).optional(),
  panels: z.array(panelSchema).min(1).max(24),
  noWrapPaths: z.array(pathField).max(12).default([]),
});

export const studioAuthorPayloadSchema = z.object({
  viewBox: z.object({ width: z.number().positive(), height: z.number().positive() }),
  views: z.array(viewSchema).min(1).max(5),
  // Free-text provenance note appended to the generated metadata (license wall).
  provenanceNote: z.string().trim().min(10).max(500),
});

export type StudioAuthorPayload = z.infer<typeof studioAuthorPayloadSchema>;

export type AssembledOutline = {
  svgText: string;
  declaredViews: string[];
  panels: PanelInput[];
  /** Per-view mm-per-unit factors, for UI display + the layout sheet callouts. */
  mmPerUnitByView: Record<string, number>;
};

export type AssembleError = { field: string; message: string };

export type AssembleResult =
  | { ok: true; assembled: AssembledOutline }
  | { ok: false; errors: AssembleError[] };

function slugFor(vehicle: Pick<VehicleDetail, 'year' | 'make' | 'model'>): string {
  return `${vehicle.year}-${vehicle.make}-${vehicle.model}`
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

export function assembleOutline(vehicle: VehicleDetail, rawPayload: unknown): AssembleResult {
  const parsed = studioAuthorPayloadSchema.safeParse(rawPayload);
  if (!parsed.success) {
    return {
      ok: false,
      errors: parsed.error.issues.map((i) => ({ field: i.path.join('.'), message: i.message })),
    };
  }
  const payload = parsed.data;

  const seen = new Set<string>();
  for (const v of payload.views) {
    if (seen.has(v.view)) {
      return { ok: false, errors: [{ field: 'views', message: `Duplicate view "${v.view}".` }] };
    }
    seen.add(v.view);
  }

  const dims = { lengthMm: vehicle.lengthMm, widthMm: vehicle.widthMm, heightMm: vehicle.heightMm };
  const mmPerUnitByView: Record<string, number> = {};
  const errors: AssembleError[] = [];

  // Calibration first — wrap-safe generation needs mm-per-unit for the inset.
  for (const v of payload.views) {
    try {
      mmPerUnitByView[v.view] = svg.mmPerUnitFor(dims, {
        spanUnits: v.spanUnits,
        axis: v.axis ?? svg.defaultAxisForView(v.view),
      });
    } catch (err) {
      errors.push({ field: `views.${v.view}`, message: (err as Error).message });
    }
  }
  if (errors.length > 0) return { ok: false, errors };

  // Generate missing wrap-safe paths: 12 mm real-world inset, in document units.
  const viewSpecs = payload.views.map((v) => ({
    view: v.view,
    translate: v.translate,
    noWrapPaths: v.noWrapPaths,
    panels: v.panels.map((p, idx) => {
      let wrapSafePath = p.wrapSafePath;
      if (!wrapSafePath) {
        const insetUnits = WRAP_SAFE_INSET_MM / mmPerUnitByView[v.view]!;
        try {
          wrapSafePath = geometry.insetRingPath(p.outlinePath, insetUnits);
        } catch (err) {
          errors.push({
            field: `views.${v.view}.panels.${idx}`,
            message: `Cannot generate the wrap-safe inset for "${p.name}": ${(err as Error).message}`,
          });
          wrapSafePath = p.outlinePath; // placeholder; errors abort below
        }
      }
      return {
        name: p.name,
        outlinePath: p.outlinePath,
        wrapSafePath,
        finishHint: p.finishHint,
        installOrder: p.installOrder,
        notes: p.notes ?? null,
      };
    }),
  }));
  if (errors.length > 0) return { ok: false, errors };

  const svgText = svg.buildOutlineSvg({
    viewBox: payload.viewBox,
    vehicleSlug: slugFor(vehicle),
    metadata:
      `Alpha Wolf Wrap Studio — authored in Template Studio. ` +
      `Provenance: ${payload.provenanceNote} ` +
      `Not derived from any third-party template SVG.`,
    views: viewSpecs,
  });

  const declaredViews = payload.views.map((v) => v.view);
  const validated = svg.validateOutlineSvg(svgText, dims, { views: declaredViews });
  if (!validated.ok) {
    return {
      ok: false,
      errors: validated.errors.map((e) => ({ field: `svg.${e.rule}`, message: e.message })),
    };
  }

  const panels: PanelInput[] = validated.panels.map((p) => ({
    name: p.name,
    view: p.view,
    svgPath: p.outlinePath,
    wrapSafeZone: svg.wrapSafeZoneFor(p),
    printableAreaMm2: Math.round(geometry.pathAreaScaled(p.wrapSafePath, mmPerUnitByView[p.view]!)),
    finishHint: p.finishHint,
    installOrder: p.installOrder,
    notes: p.notes,
  }));

  const zeroArea = panels.filter((p) => p.printableAreaMm2 <= 0);
  if (zeroArea.length > 0) {
    return {
      ok: false,
      errors: zeroArea.map((p) => ({
        field: `panels.${p.name}`,
        message: 'Panel has zero printable area after calibration.',
      })),
    };
  }

  return { ok: true, assembled: { svgText, declaredViews, panels, mmPerUnitByView } };
}
