// Vehicle template repository (GH-003 / GH-004).
//
// Two access shapes, matching the RLS model (see prisma/sql/auth_rls.sql):
//   * Public browse/search/detail run on withSystem() — vehicle templates are
//     shared, public, NON-PII catalog data with no per-user scoping. withSystem
//     bypasses RLS, so EVERY public function here MUST filter status='published'
//     itself; the published-only guarantee for that path lives in these queries,
//     not in RLS.
//   * Admin CRUD runs on withUser(adminId) — RLS enforces admin-only writes via
//     app_is_admin(), and lets the admin read every status.
//
// Never expose the Prisma client. Callers get plain row objects.

import type { Prisma } from '@prisma/client';
import type { BodyType, FinishHint, SourceAuthority, TemplateStatus } from '@prisma/client';
import { pgQuoteLiteral, withSystem, withUser } from '../client.js';

export type { BodyType, FinishHint, SourceAuthority, TemplateStatus };

export type VehicleSummary = {
  id: string;
  year: number;
  make: string;
  model: string;
  trim: string | null;
  variant: string | null;
  bodyType: BodyType;
  lengthMm: number;
  widthMm: number;
  heightMm: number;
  outlineSvgUrl: string;
  thumbPngUrl: string;
  status: TemplateStatus;
  version: number;
};

export type PanelInput = {
  name: string;
  view: string;
  svgPath: string;
  wrapSafeZone: Prisma.InputJsonValue;
  printableAreaMm2: number;
  finishHint: FinishHint;
  installOrder: number;
  notes?: string | null;
};

export type PanelRecord = PanelInput & { id: string };

// Alpha Wolf wrapped-template metadata (Goal 2a). Null on non-AW rows.
export type AlphaWolfTemplateFields = {
  svgStorageKey: string | null;
  viewCount: number | null;
  dimensionsText: string | null;
  scaleDenom: number;
  alphaWolfTplId: string | null;
};

export type VehicleDetail = VehicleSummary &
  AlphaWolfTemplateFields & {
    variant: string | null;
    wheelbaseMm: number | null;
    cabSize: string | null;
    bedSize: string | null;
    roofHeight: string | null;
    doorCount: number | null;
    topviewSvgUrl: string | null;
    sourceAuthority: SourceAuthority;
    sourceNotes: string | null;
    verifiedAt: Date | null;
    supersedesId: string | null;
    createdAt: Date;
    updatedAt: Date;
    panels: PanelRecord[];
  };

// Curated catalogue card for the /vehicles browse grid. AW rows only.
export type AlphaWolfTemplateCard = {
  id: string;
  year: number;
  make: string;
  model: string;
  trim: string | null;
  bodyType: BodyType;
  thumbPngUrl: string;
  viewCount: number | null;
  scaleDenom: number;
  dimensionsText: string | null;
  alphaWolfTplId: string;
};

export type CreateVehicleInput = {
  id: string; // generated by the caller so assets can be named before insert
  year: number;
  make: string;
  model: string;
  trim?: string | null;
  variant?: string | null;
  bodyType: BodyType;
  lengthMm: number;
  widthMm: number;
  heightMm: number;
  wheelbaseMm?: number | null;
  cabSize?: string | null;
  bedSize?: string | null;
  roofHeight?: string | null;
  doorCount?: number | null;
  outlineSvgUrl: string;
  topviewSvgUrl?: string | null;
  thumbPngUrl: string;
  sourceAuthority: SourceAuthority;
  sourceNotes?: string | null;
  panels: PanelInput[];
};

export type CascadeFilter = {
  year?: number;
  make?: string;
  model?: string;
  trim?: string | null;
  bodyType?: BodyType;
  cabSize?: string;
  bedSize?: string;
  roofHeight?: string;
};

export type VehicleFacets = {
  bodyTypes: BodyType[];
  cabSizes: string[];
  bedSizes: string[];
  roofHeights: string[];
};

const SUMMARY_SELECT = {
  id: true,
  year: true,
  make: true,
  model: true,
  trim: true,
  variant: true,
  bodyType: true,
  lengthMm: true,
  widthMm: true,
  heightMm: true,
  outlineSvgUrl: true,
  thumbPngUrl: true,
  status: true,
  version: true,
} satisfies Prisma.VehicleSelect;

// ----------------------------------------------------------------------------
// Pure query/where builders — no DB access, unit-tested directly.
// ----------------------------------------------------------------------------

// Translate a cascade/facet filter into a Prisma where clause, always pinned to
// published rows. Empty/undefined fields are omitted so each cascade level
// widens correctly. trim is tri-state: `null` means "base trim (no trim)",
// undefined means "any trim".
export function buildPublishedWhere(filter: CascadeFilter): Prisma.VehicleWhereInput {
  const where: Prisma.VehicleWhereInput = { status: 'published' };
  if (filter.year !== undefined) where.year = filter.year;
  if (filter.make) where.make = filter.make;
  if (filter.model) where.model = filter.model;
  if (filter.trim !== undefined) where.trim = filter.trim;
  if (filter.bodyType) where.bodyType = filter.bodyType;
  if (filter.cabSize) where.cabSize = filter.cabSize;
  if (filter.bedSize) where.bedSize = filter.bedSize;
  if (filter.roofHeight) where.roofHeight = filter.roofHeight;
  return where;
}

// The searchable text expression — kept byte-identical to the tsvector and
// trigram indexes in the migration so the planner can use them.
const SEARCH_EXPR =
  "coalesce(make,'') || ' ' || coalesce(model,'') || ' ' || " +
  "coalesce(trim,'') || ' ' || coalesce(variant,'') || ' ' || year::text";

// Build the typo-tolerant search SQL. Combines a pg_trgm similarity match (for
// typos: "transt 250" -> "Transit 250") with an AND of per-term ILIKE
// substring matches (for precise multi-field queries: "2024 transit 250").
// Values are escaped via pgQuoteLiteral — the only safe raw-SQL shape on the
// transaction pooler (see client.ts). Returns null when the query is blank.
export function buildVehicleSearchSql(query: string, limit = 50): string | null {
  const q = query.trim();
  if (!q) return null;
  const terms = q.split(/\s+/).filter(Boolean).slice(0, 8);
  const trigram = `(${SEARCH_EXPR}) % ${pgQuoteLiteral(q)}`;
  const termIlikes = terms
    .map((t) => `(${SEARCH_EXPR}) ILIKE ${pgQuoteLiteral(`%${t}%`)}`)
    .join(' AND ');
  const lim = Math.max(1, Math.min(200, Math.trunc(limit)));
  return `
    SELECT id, year, make, model, trim, variant, body_type AS "bodyType",
           length_mm AS "lengthMm", width_mm AS "widthMm", height_mm AS "heightMm",
           outline_svg_url AS "outlineSvgUrl", thumb_png_url AS "thumbPngUrl",
           status, version,
           similarity((${SEARCH_EXPR}), ${pgQuoteLiteral(q)}) AS sim
    FROM vehicles
    WHERE status = 'published'
      AND ( ${trigram} OR (${termIlikes}) )
    ORDER BY sim DESC, year DESC, make ASC, model ASC
    LIMIT ${lim}`;
}

// Reduce a set of published rows to the distinct facet values present, so the UI
// only ever offers facets that resolve to a real template. Pure — unit-tested.
export function summariseFacets(
  rows: Array<{
    bodyType: BodyType;
    cabSize: string | null;
    bedSize: string | null;
    roofHeight: string | null;
  }>,
): VehicleFacets {
  const uniq = <T>(xs: Array<T | null | undefined>): T[] =>
    [...new Set(xs.filter((x): x is T => x != null))].sort();
  return {
    bodyTypes: uniq(rows.map((r) => r.bodyType)),
    cabSizes: uniq(rows.map((r) => r.cabSize)),
    bedSizes: uniq(rows.map((r) => r.bedSize)),
    roofHeights: uniq(rows.map((r) => r.roofHeight)),
  };
}

// ----------------------------------------------------------------------------
// Public read path (withSystem; published-only is enforced HERE).
// ----------------------------------------------------------------------------

export async function listYears(): Promise<number[]> {
  return withSystem(async (db) => {
    const rows = await db.vehicle.findMany({
      where: { status: 'published' },
      distinct: ['year'],
      select: { year: true },
      orderBy: { year: 'desc' },
    });
    return rows.map((r) => r.year);
  });
}

export async function listMakes(year: number): Promise<string[]> {
  return withSystem(async (db) => {
    const rows = await db.vehicle.findMany({
      where: { status: 'published', year },
      distinct: ['make'],
      select: { make: true },
      orderBy: { make: 'asc' },
    });
    return rows.map((r) => r.make);
  });
}

export async function listModels(year: number, make: string): Promise<string[]> {
  return withSystem(async (db) => {
    const rows = await db.vehicle.findMany({
      where: { status: 'published', year, make },
      distinct: ['model'],
      select: { model: true },
      orderBy: { model: 'asc' },
    });
    return rows.map((r) => r.model);
  });
}

export async function listTrims(
  year: number,
  make: string,
  model: string,
): Promise<Array<string | null>> {
  return withSystem(async (db) => {
    const rows = await db.vehicle.findMany({
      where: { status: 'published', year, make, model },
      distinct: ['trim'],
      select: { trim: true },
      orderBy: { trim: 'asc' },
    });
    return rows.map((r) => r.trim);
  });
}

export async function getFacets(year: number, make: string, model: string): Promise<VehicleFacets> {
  return withSystem(async (db) => {
    const rows = await db.vehicle.findMany({
      where: { status: 'published', year, make, model },
      select: { bodyType: true, cabSize: true, bedSize: true, roofHeight: true },
    });
    return summariseFacets(rows);
  });
}

export async function findPublished(filter: CascadeFilter): Promise<VehicleSummary[]> {
  return withSystem(async (db) => {
    return db.vehicle.findMany({
      where: buildPublishedWhere(filter),
      select: SUMMARY_SELECT,
      orderBy: [{ year: 'desc' }, { make: 'asc' }, { model: 'asc' }, { trim: 'asc' }],
      take: 100,
    });
  });
}

export async function searchPublished(query: string): Promise<VehicleSummary[]> {
  const sql = buildVehicleSearchSql(query);
  if (!sql) return [];
  return withSystem(async (db) => {
    // Loosen the trigram threshold for short/typo queries (default 0.3). Local
    // to this transaction so it can't leak across pool reuse.
    await db.$executeRawUnsafe(`SELECT set_config('pg_trgm.similarity_threshold', '0.2', true)`);
    const rows = await db.$queryRawUnsafe<Array<VehicleSummary & { sim: number }>>(sql);
    return rows.map(({ sim: _sim, ...v }) => v);
  });
}

export async function getPublishedDetail(id: string): Promise<VehicleDetail | null> {
  return withSystem(async (db) => {
    const v = await db.vehicle.findFirst({
      where: { id, status: 'published' },
      include: { panels: { orderBy: { installOrder: 'asc' } } },
    });
    return v ? toDetail(v) : null;
  });
}

// Curated Alpha Wolf catalogue for the /vehicles browse grid (Goal 2a). Returns
// only published rows that carry an AW-TPL id, newest-catalogued first
// (alpha_wolf_tpl_id ascending keeps AW-TPL-0001..0003 in a stable order). Runs
// on withSystem (public, non-PII catalogue data) — so it filters status itself.
export async function listAlphaWolfTemplates(): Promise<AlphaWolfTemplateCard[]> {
  return withSystem(async (db) => {
    const rows = await db.vehicle.findMany({
      where: { status: 'published', alphaWolfTplId: { not: null } },
      select: {
        id: true,
        year: true,
        make: true,
        model: true,
        trim: true,
        bodyType: true,
        thumbPngUrl: true,
        viewCount: true,
        scaleDenom: true,
        dimensionsText: true,
        alphaWolfTplId: true,
      },
      orderBy: { alphaWolfTplId: 'asc' },
    });
    // alphaWolfTplId is non-null by the where filter; narrow the type for callers.
    return rows.map((r) => ({ ...r, alphaWolfTplId: r.alphaWolfTplId as string }));
  });
}

// ----------------------------------------------------------------------------
// Admin path (withUser(adminId); RLS enforces admin-only writes).
// ----------------------------------------------------------------------------

export async function adminListVehicles(adminId: string): Promise<VehicleSummary[]> {
  return withUser(adminId, async (db) => {
    return db.vehicle.findMany({
      select: SUMMARY_SELECT,
      orderBy: [{ updatedAt: 'desc' }],
      take: 500,
    });
  });
}

export async function adminGetDetail(adminId: string, id: string): Promise<VehicleDetail | null> {
  return withUser(adminId, async (db) => {
    const v = await db.vehicle.findUnique({
      where: { id },
      include: { panels: { orderBy: { installOrder: 'asc' } } },
    });
    return v ? toDetail(v) : null;
  });
}

export async function createVehicle(adminId: string, input: CreateVehicleInput): Promise<string> {
  return withUser(adminId, async (db) => {
    const created = await db.vehicle.create({
      data: {
        id: input.id,
        year: input.year,
        make: input.make,
        model: input.model,
        trim: input.trim ?? null,
        variant: input.variant ?? null,
        bodyType: input.bodyType,
        lengthMm: input.lengthMm,
        widthMm: input.widthMm,
        heightMm: input.heightMm,
        wheelbaseMm: input.wheelbaseMm ?? null,
        cabSize: input.cabSize ?? null,
        bedSize: input.bedSize ?? null,
        roofHeight: input.roofHeight ?? null,
        doorCount: input.doorCount ?? null,
        outlineSvgUrl: input.outlineSvgUrl,
        topviewSvgUrl: input.topviewSvgUrl ?? null,
        thumbPngUrl: input.thumbPngUrl,
        sourceAuthority: input.sourceAuthority,
        sourceNotes: input.sourceNotes ?? null,
        status: 'draft',
        panels: {
          create: input.panels.map((p) => ({
            name: p.name,
            view: p.view,
            svgPath: p.svgPath,
            wrapSafeZone: p.wrapSafeZone,
            printableAreaMm2: p.printableAreaMm2,
            finishHint: p.finishHint,
            installOrder: p.installOrder,
            notes: p.notes ?? null,
          })),
        },
      },
      select: { id: true },
    });
    return created.id;
  });
}

// Publish a draft/review row. Enforces "one published per (year,make,model,trim,
// variant)" by retiring any currently-published sibling first — the matching
// partial unique index (vehicles_published_uk) is the backstop. Records the
// verifying admin per the spec §6 publish step.
export async function publishVehicle(adminId: string, id: string): Promise<void> {
  await withUser(adminId, async (db) => {
    const target = await db.vehicle.findUnique({
      where: { id },
      select: { year: true, make: true, model: true, trim: true, variant: true },
    });
    if (!target) throw new Error('[db] publishVehicle: vehicle not found');

    await db.vehicle.updateMany({
      where: {
        status: 'published',
        year: target.year,
        make: target.make,
        model: target.model,
        trim: target.trim,
        variant: target.variant,
        id: { not: id },
      },
      data: { status: 'retired' },
    });

    await db.vehicle.update({
      where: { id },
      data: { status: 'published', verifiedAt: new Date(), verifiedById: adminId },
    });
  });
}

export async function setVehicleStatus(
  adminId: string,
  id: string,
  status: TemplateStatus,
): Promise<void> {
  await withUser(adminId, async (db) => {
    await db.vehicle.update({ where: { id }, data: { status } });
  });
}

// Clone a vehicle into a fresh draft for the next version (spec §6 / GH-004
// "edits create a new version; older versions remain"). Copies metadata, asset
// URLs, and panels; the new draft supersedes the source.
export async function createNewVersion(adminId: string, sourceId: string): Promise<string> {
  return withUser(adminId, async (db) => {
    const src = await db.vehicle.findUnique({
      where: { id: sourceId },
      include: { panels: true },
    });
    if (!src) throw new Error('[db] createNewVersion: source not found');
    const cloned = await db.vehicle.create({
      data: {
        year: src.year,
        make: src.make,
        model: src.model,
        trim: src.trim,
        variant: src.variant,
        bodyType: src.bodyType,
        lengthMm: src.lengthMm,
        widthMm: src.widthMm,
        heightMm: src.heightMm,
        wheelbaseMm: src.wheelbaseMm,
        cabSize: src.cabSize,
        bedSize: src.bedSize,
        roofHeight: src.roofHeight,
        doorCount: src.doorCount,
        outlineSvgUrl: src.outlineSvgUrl,
        topviewSvgUrl: src.topviewSvgUrl,
        thumbPngUrl: src.thumbPngUrl,
        sourceAuthority: src.sourceAuthority,
        sourceNotes: src.sourceNotes,
        version: src.version + 1,
        status: 'draft',
        supersedesId: src.id,
        panels: {
          create: src.panels.map((p) => ({
            name: p.name,
            view: p.view,
            svgPath: p.svgPath,
            wrapSafeZone: p.wrapSafeZone as Prisma.InputJsonValue,
            printableAreaMm2: p.printableAreaMm2,
            finishHint: p.finishHint,
            installOrder: p.installOrder,
            notes: p.notes,
          })),
        },
      },
      select: { id: true },
    });
    return cloned.id;
  });
}

// Row -> VehicleDetail. `v` is a Prisma vehicle with `panels` included.
function toDetail(v: Prisma.VehicleGetPayload<{ include: { panels: true } }>): VehicleDetail {
  return {
    id: v.id,
    year: v.year,
    make: v.make,
    model: v.model,
    trim: v.trim,
    variant: v.variant,
    bodyType: v.bodyType,
    lengthMm: v.lengthMm,
    widthMm: v.widthMm,
    heightMm: v.heightMm,
    outlineSvgUrl: v.outlineSvgUrl,
    thumbPngUrl: v.thumbPngUrl,
    status: v.status,
    version: v.version,
    svgStorageKey: v.svgStorageKey,
    viewCount: v.viewCount,
    dimensionsText: v.dimensionsText,
    scaleDenom: v.scaleDenom,
    alphaWolfTplId: v.alphaWolfTplId,
    wheelbaseMm: v.wheelbaseMm,
    cabSize: v.cabSize,
    bedSize: v.bedSize,
    roofHeight: v.roofHeight,
    doorCount: v.doorCount,
    topviewSvgUrl: v.topviewSvgUrl,
    sourceAuthority: v.sourceAuthority,
    sourceNotes: v.sourceNotes,
    verifiedAt: v.verifiedAt,
    supersedesId: v.supersedesId,
    createdAt: v.createdAt,
    updatedAt: v.updatedAt,
    panels: v.panels.map((p) => ({
      id: p.id,
      name: p.name,
      view: p.view,
      svgPath: p.svgPath,
      wrapSafeZone: p.wrapSafeZone as Prisma.InputJsonValue,
      printableAreaMm2: p.printableAreaMm2,
      finishHint: p.finishHint,
      installOrder: p.installOrder,
      notes: p.notes,
    })),
  };
}
